### ISSUE TITLE
Not listed on PyPI

### ISSUE THREAD

**Issue by Swang007** [thycotic/python-tss-sdk#1]
I'm looking to use this SDK, and is crucial to my team that it is installable via pip (for portability reasons). Unfortunately, I cannot install the module via pip as it does not seem to exist in the PyPI library.

Following these instructions on the README:
![image](https://user-images.githubusercontent.com/11000109/77014281-ee4b7480-693f-11ea-9967-4e194273ed4c.png)

result in the following error:
![image](https://user-images.githubusercontent.com/11000109/77014333-08855280-6940-11ea-9e32-29119f4d3ae0.png)

**Comment by wsmelton** [comment]
I'm not able to duplicate this error in Python 3.8.

Python 3.6 or higher is required for this package to be utilized.

**Comment by Swang007** [comment]
We are using Python 3.6.8. The issue was that the package was not available on PyPi. It seems this has since been published on March 30:
https://pypi.org/project/python-tss-sdk/
