### ISSUE TITLE
Add ability to load a secret by name/path

### ISSUE THREAD

**Issue by rossbeehler** [thycotic/python-tss-sdk#10]
Evaluating the related ansible tss lookup plugin, and it doesn't feel very useful to have to know the ID of the secret to load.  Should we instead have a mechanism to load by secret name or full directory path + name (as name isn't unique), etc.?

**Comment by Benvandamme** [comment]
Same here! I second this.

**Comment by amigus** [comment]
I think that the ability to store multiple secrets by the same name (unless it's disabled via the configuration) makes this to complex and error-prone to add to the SDK. Instead, I recommend asking for this as a Feature Request of the API itself. Once the API implements it, exposing that via the SDK makes sense.

**Comment by cacack** [comment]
Maybe things have changed recently, but the REST API docs do provide a `/secrets` endpoint which accepts a bunch of filter parameters and returns a response containing a list of the matching secret objects.

https://updates.thycotic.net/secretserver/restapiguide/10.9.33/TokenAuth/#operation--secrets-get

**Comment by wsmelton** [comment]
As of 11.0 the `GET v1/folders/{id}` and `GET /v1/secrets/{id}` both support pulling a Secret via the path.
