### ISSUE TITLE
dataclasses is not getting downloaded

### ISSUE THREAD

**Issue by samthar** [thycotic/python-tss-sdk#2]
When you do the "pip3 install python-tss-sdk --user" it doesn't seem to pull, dataclasses.py as part of the install

./thycotic
./thycotic/secrets
./thycotic/secrets/__pycache__
./thycotic/secrets/__pycache__/dataclasses.cpython-38.pyc
./thycotic/secrets/__pycache__/__init__.cpython-38.pyc
./thycotic/secrets/__pycache__/server.cpython-38.pyc
./thycotic/secrets/__pycache__/test_server.cpython-38.pyc
./thycotic/secrets/__init__.py
./thycotic/secrets/server.py
./thycotic/secrets/test_server.py
./thycotic/__init__.py
./thycotic/__pycache__
./thycotic/__pycache__/__init__.cpython-38.pyc

**Comment by austinnichols101** [comment]
@amigus - can you check that PyPi has the latest build?  Confirming the reports above ^^ that the build does not contain `dataclasses.py`.  Please advise...

https://pypi.org/project/python-tss-sdk/0.0.1/

![image](https://user-images.githubusercontent.com/6962379/91593454-2ebb0f80-e92e-11ea-8e4d-b4dabf1d4c83.png)

**Comment by amigus** [comment]
The latest has been uploaded.  Sorry for the wait!
