### ISSUE TITLE
Ansible Lookup plugin (community.general.tss) is broken with version 1.0.0

### ISSUE THREAD

**Issue by tomreeb** [thycotic/python-tss-sdk#27]
Updates to the python-tss-sdk have broken the Ansible Lookup plugin (community.general.tss). 

```
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{{ lookup('community.general.tss', 12345) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'community.general.tss'. Error was a <class 'ansible.errors.AnsibleError'>, original message: python-tss-sdk must be installed to use this plugin"
}
```

**Comment by tomreeb** [comment]
More context:
This error is being raised despite my pipelines working fine with 0.0.6. Looking at the tss.py:

```
try:
    from thycotic.secrets.server import (
        SecretServer,
        SecretServerAccessError,
        SecretServerError,
    )
except ImportError:
    sdk_is_missing = True
```

Did 1.0.0 remove the SecretServerAccessError class?

**Comment by EndlessTrax** [comment]
We released this new SDK version yesterday, and it introduced breaking changes. Now version 1.0.0 is live, we'll be updating all the other integrations and plugins (like Ansible) to reflect those changes. Please ensure you're pinning v0.0.6 for now until that plugin is updated.

**Comment by EndlessTrax** [comment]
I fixed this in a recent PR (https://github.com/ansible-collections/community.general/pull/3139)

Please be sure to update when the next release is published.
