### ISSUE TITLE
How to use MFA? I dont see an option to provide RSA token in class SecretServer

### ISSUE THREAD

**Issue by navjyotnishant** [thycotic/python-tss-sdk#3]

**Comment by amigus** [comment]
The underlying API doesn't support MFA authentication so this SDK API cannot either. Sorry.

**Comment by navjyotnishant** [comment]
What would be the way if i have to implement solution with MFA? currenty we do have MFA enabled for secret server and we are looking to imcorporate the same functionality.

**Comment by amigus** [comment]
The norm is to use MFA when calling the API (as opposed to the web UI) because usually, the goal is to automate something. Either way, Thycotic has not implemented it to date.

**Comment by briancline** [comment]
It appears this actually is implemented, just not listed as a field in the token auth API docs. However, the official API scripting documentation does include a REST API example written in Powershell where an optional `OTP` field is included in the POST payload for providing a 2FA key:
https://docs.thycotic.com/ss/10.9.0/api-scripting/rest-api-powershell-examples/index.md

We're using 10.9.0 and including this field does seem to work, even for RADIUS auth.
