### ISSUE TITLE
Error - README.md

### ISSUE THREAD

**Issue by chadtsigler** [thycotic/python-tss-sdk#30]
https://github.com/thycotic/python-tss-sdk#initializing-secretserver

Example:
`from thycotic.secrets.server import ServerSecret
`

Should be
`from thycotic.secrets.server import SecretServer
`

**Comment by EndlessTrax** [comment]
Good catch! Thank you.

**Comment by EndlessTrax** [comment]
Fixed in commit https://github.com/thycotic/python-tss-sdk/commit/8db1d41650d0f2bf45fb9316bb7d33093ab75986
