### ISSUE TITLE
dataclasses.py ValueError: Invalid isoformat string: '2020-08-31T20:09:29.3'

### ISSUE THREAD

**Issue by codyrat** [thycotic/python-tss-sdk#6]
Traceback (most recent call last):
  File "/thycotic-tss/thycotic_getsecret.py", line 22, in <module>
    secret = ServerSecret(**secret_server.get_secret(SECRET_ID))
  File "thycotic-tss-nAi62Izf/lib/python3.8/site-packages/thycotic/secrets/dataclasses.py", line 65, in __init__
    v = datetime.fromisoformat(v)
ValueError: Invalid isoformat string: '2020-08-31T20:09:29.3'

dataclasses seems to be receiving a timestamp in non-zero padded format and should be '2020-08-31T20:09:29.300000'

**Comment by wsmelton** [comment]
Fixed in 584f11b

**Comment by wsmelton** [comment]
Opening this as I can replicate this against an Secret Server Cloud subscription. It works fine on an on-premise instance though.

**Comment by amigus** [comment]
I think the error you're getting now is different. I just logged and closed #8 to address it.
