### ISSUE TITLE
Search method that providers Secret ID a given account has rights to access

### ISSUE THREAD

**Issue by wsmelton** [thycotic/python-tss-sdk#9]
(_Via customer engagement_)

The request is to have a method that allows pulling a dictionary of secrets that a given Secret Server user has permissions to access. This would be to do a dynamic lookup for that Secret ID that the `get_secret()` method requires.

**Comment by amigus** [comment]
I don't see a reason to add this. Access auditing should be handled via the reporting function...

**Comment by wsmelton** [comment]
This is not around any auditing use cases.

The purpose would be to provide a call to the search endpoint. If you hit that endpoint on the REST API with no parameters provided it returns every secret the given user has rights to see. This prevents the need for the author to look up the ID we require in `get_secret()`.
